### ISSUE TITLE
How to use full Mediawiki template expansion

### ISSUE THREAD

**Issue by knub** [sweble/sweble-wikitext#29]
Hi,

the announcement post for Sweble 2.0 mentions template expansion.
I can't find how to do that.

Can you give me/point me to a short example?

**Comment by sweble** [comment]
Hi,

have a look at https://github.com/sweble/sweble-wikitext/blob/develop/swc-example-basic/src/main/java/org/sweble/wikitext/example/App.java, line 95: The last argument to the engine.postprocess(pageId, wikitext, null); call is null. If you implement the interface org.sweble.wikitext.engine.ExpansionCallback and pass an instance to the postprocess() method, the callback will be used to fetch wiki markup for transclusions. Also, a non-null expansion callback parameter will turn on expansion in general (parser functions, tag extensions, etc.). Just returning null in the callback methods will work, if you don't need transclusions.

Please be aware that expansion of transclusions should work fine, however, only a small subset of tag extensions and parser functions that would normally be available in a MediaWiki are implemented in Sweble.

Cheers
Hannes

**Comment by knub** [comment]
Thanks for that!
