### ISSUE TITLE
No jars on maven central

### ISSUE THREAD

**Issue by burtonator** [sweble/sweble-wikitext#38]
I'm not sure why but none of your .jars are actually on maven central.

https://repo1.maven.org/maven2/org/sweble/sweble/2.0.0/

only .pom files.  I tried pulling right from maven central and it doesn't work.

**Comment by burtonator** [comment]
Weird.. same thing for your snapshots here:

https://mojo-maven.cs.fau.de/content/repositories/public/org/sweble/sweble/

no .jar files.. only poms...

**Comment by hannesd** [comment]
Hi, not sure if I'm overlooking something, but the pom you mention is a pure pom project used as parent for other maven modules that actually do have their .jar files. I've browsed maven central a bit and so far I think all .jar files are there. The following maven modules are pom only: hddiff-project, parser-toolkit, sweble-engine, sweble-wikitext, sweble-wom3, sweble, tooling

**Comment by burtonator** [comment]
Thanks.  It's weird because I've used pom only projects before and they work fine but I'm still having issues with the above modules.

I'll try to debug it more...

**Comment by burtonator** [comment]
OK.  I can confirm that it's trying to download the .jar files... they 404 of course.  

This is on an empty project I created just to debug which just has dependencies. 

```
Downloading: https://repo.maven.apache.org/maven2/org/sweble/sweble/2.0.0/sweble-2.0.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/sweble/wom3/sweble-wom3/2.0.0/sweble-wom3-2.0.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/sweble/engine/sweble-engine/2.0.0/sweble-engine-2.0.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/sweble/wikitext/sweble-wikitext/2.0.0/sweble-wikitext-2.0.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.777 s
[INFO] Finished at: 2015-12-08T09:06:44-08:00
[INFO] Final Memory: 22M/964M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sweble-test: Could not resolve dependencies for project sweble-test:sweble-test:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: org.sweble:sweble:jar:2.0.0, org.sweble.engine:sweble-engine:jar:2.0.0, org.sweble.wom3:sweble-wom3:jar:2.0.0, org.sweble.wikitext:sweble-wikitext:jar:2.0.0: Could not find artifact org.sweble:sweble:jar:2.0.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]


```

**Comment by hannesd** [comment]
My best guess right now is that you directly mention the POM-only modules as dependencies in your own POM. Could you paste the Sweble related dependencies from your POM?
