### ISSUE TITLE
Version 2.1.0 source code

### ISSUE THREAD

**Issue by sfragis** [sweble/sweble-wikitext#40]
Version 2.1.0 can be found on Maven ([http://mvnrepository.com/artifact/org.sweble.wikitext/swc-example-basic/2.1.0](http://mvnrepository.com/artifact/org.sweble.wikitext/swc-example-basic/2.1.0)) but there's no trace of it in any branch. Is this the main Git repository still?

**Comment by hannesd** [comment]
This is still the main (public) repository. However, synchronization between our internal repo and github is currently broken. I hope I can fix this today.

**Comment by hannesd** [comment]
Sorry for the delay. The changes have been pushed.

**Comment by sfragis** [comment]
Thank you
