### ISSUE TITLE
pre tag support is case sensitive

### ISSUE THREAD

**Issue by kno10** [sweble/sweble-wikitext#43]
Apparently, pages such as `Data Transformation Services` in enwiki and `Dynamic programming` fail because the pre tag extension is case-sensitive, i.e. it only triggers for `<pre>` not for `<PRE>`?

**Comment by kno10** [comment]
There is also a related hack in [Template:Pre2](https://en.wikipedia.org/w/index.php?title=Template:Pre2&action=edit) that can be simplified to:
```
<pre<includeonly/>>Test''b''</pre>
```
that is apparently designed to bypass the special handling of `<pre>` tags. It allows (as in this example) wiki markup within pre tags.

**Comment by hannesd** [comment]
Fixed in version 2.2.0
