### ISSUE TITLE
The title `Template:Did you know nominations/Steve Taylor & The Perfect Foil; Wow to the Deadness' contains invalid entities: &_The_Perfect_Foil;

### ISSUE THREAD

**Issue by kno10** [sweble/sweble-wikitext#45]
As the error indicates, links to this page will parse as invalid entites, even when written with space, because `&_The_Perfect_Foil;` apparently would be a valid XML entity name.

The error is in
org.sweble.wikitext.parser.parser.LinkTargetParser.parse(LinkTargetParser.java:180)

Maybe the logic can be changed, and the sanity check moved before the entity matching (e.g. after `xmlDecode`)?

The line `result = StringUtils.trim(result);` can probably be removed - afterwards, whitespace is substituted with underscores, and underscores are trimmed again.

**Comment by hannesd** [comment]
Fixed in version 2.2.0
