### ISSUE TITLE
Parsing of external links with bars

### ISSUE THREAD

**Issue by kno10** [sweble/sweble-wikitext#55]
For example on [dewiki:Ruprecht-Karls-Universität Heidelberg](https://de.wikipedia.org/w/index.php?title=Ruprecht-Karls-Universit%C3%A4t_Heidelberg&oldid=147812863)
there is an external link with a bar inside:
```
[http://www.cos.uni-heidelberg.de/index.php/sfb873?|SFB&l=_e SFB 873]
                                            ouch --^        ^-- real separator of link title
```
this works with Wikipedia, but does not in Sweble for me.

But it is a rare corner case.

**Comment by hannesd** [comment]
The above link is now parsed correctly. However, the fix was not straight forward and caused problems elsewhere in link parsing. This led to a bigger refactoring. Long story short: Though all tests are green again this fix may have introduced some new bugs...
