### ISSUE TITLE
Wikilinks with postfix and umlaut

### ISSUE THREAD

**Issue by kno10** [sweble/sweble-wikitext#56]
https://de.wikipedia.org/w/index.php?title=Tracey_Ullman&oldid=159855475

```
ist eine [[Vereinigtes Königreich|britisch]]stämmige [[Schauspielerin]] und
```

instead of `britischstämmige`, the link only covers `britischst`.

**Comment by hannesd** [comment]
What does your parser config look like? There's the option "<internalLinkPostfixPattern>[a-z]+</internalLinkPostfixPattern>"  in the English default configuration provided in the Sweble repo. For the german version you would have to add Umlauts. There's also an option for a prefix pattern which is disabled in the English configuration.

**Comment by kno10** [comment]
Thank you, I had not noticed this. My config is derived from English wikipedia, so it only contained `[a-z]`. 

For future reference:
https://phabricator.wikimedia.org/source/mediawiki/browse/master/languages/messages/MessagesDe.php
contains: `/^([äöüßa-z]+)(.*)$/sDu`, so the appropriate value for German wikipedia should be `[äöüßa-z]+`.
