### ISSUE TITLE
Support for the <chem tag

### ISSUE THREAD

**Issue by physikerwelt** [sweble/sweble-wikitext#63]
Currently, there is build in support for the [math](https://github.com/sweble/sweble-wikitext/blob/master/sweble-wikitext-components-parent/swc-engine/src/main/java/org/sweble/wikitext/engine/ext/math/MathTagExt.java) extension. However, the chem tag for chemistry is not registered with the math extension. This causes that `visit(WtTagExtension n)` is called if the math tag is used but not if the chem tag is used. Is there anything one can do make sweble aware of the chem tag?

**Comment by hannesd** [comment]
We'd be happy to accept a pull request adding support for the chem tag. I'm not familiar with this particular extension myself, but it sounds like quite a bit of work...

Let me know if you have questions on how to extend Sweble.
