### ISSUE TITLE
Readme with development instructions

### ISSUE THREAD

**Issue by wetneb** [sweble/sweble-wikitext#79]
We should have a README file which indicates how to use this library (with Maven coordinates), how to get started with development on this repository (which might require cloning the osr-common repository as a parent directory?), and other useful info.

**Comment by wetneb** [comment]
Closed by [d2efc54](https://github.com/sweble/sweble-wikitext/commit/d2efc54c1efc8aa8d681d6ac0cd764b33d03e89e)

**Comment by jberkel** [comment]
@wetneb what's the state of the project? it looked abandoned for a  long time.

**Comment by wetneb** [comment]
yes it has been idle for a long time and I would be interested in cleaning up a bit of the dust around. if you feel like lending a hand, let me know!

**Comment by jberkel** [comment]
yes, sure! where is help needed at the moment?

**Comment by wetneb** [comment]
Well, if you feel like it, #83 could do with a bit of help.
Also, I have just created https://github.com/sweble/sweble.github.io which can hopefully host some documentation for the library soon:
* some content could be reused from https://web.archive.org/web/20170912094506/http://sweble.org/
* we could add javadocs

**Comment by jberkel** [comment]
Ok, I'll have a look at #83. 

Regarding the Java version, it looks like there's some modernizing to do. I first need to get the  project to build locally, it's been a while, and some dependencies ask for Java 1.6 source compatibility which isn't provided any longer by modern JDKs  :)

Regarding documentation: that's a great idea, Javadocs are useful, but I think some simple example code for common tasks  would be even better (f. ex. here's how you parse templates to extract the parameters)

I think sweble's underpinnings are solid, but the API is a bit difficult to use in some parts. 

Another important maintenance aspect would be to get the parser updated with recent changes in the Mediawiki markup spec. I'm not sure how much work that would involve.

**Comment by wetneb** [comment]
Definitely! Happy to support you in those other endeavors too :)
